version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=sqlite:///./factory_yintu.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    command: npm start
    
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"